# Generated by Django 2.0.5 on 2018-05-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.SlugField()),
                ('repo', models.SlugField()),
                ('stars', models.PositiveSmallIntegerField()),
                ('watchers', models.PositiveSmallIntegerField()),
                ('contributors', models.PositiveSmallIntegerField()),
                ('open_pr_count', models.PositiveSmallIntegerField()),
                ('open_issue_count', models.PositiveSmallIntegerField()),
                ('last_pr_closed', models.DateTimeField()),
                ('last_pr_opened', models.DateTimeField()),
                ('sync_created', models.DateTimeField(auto_now_add=True)),
                ('sync_last_updated', models.DateTimeField(auto_now_add=True)),
                ('ignore', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='githubproject',
            unique_together={('owner', 'repo')},
        ),
    ]
